### ISSUE TITLE
Publish library to maven center

### ISSUE THREAD

**Issue by Shusek** [bright/codified#2]
Hello, would it be possible to publish the library on maven center?  Unfortunately, corporate company security policy prohibits use of jitpack inside mobile application.

**Comment by azabost** [comment]
Sure. I requested a new repo in Maven Central. I'll let you know once I manage to publish it there.

**Comment by azabost** [comment]
@Shusek Hey. I think it should work now.

Please follow the updated info in README:
- use Maven Central
- update version to 1.6.21.1
- use `dev.bright.codified` as the group ID of the dependencies (instead of `com.github.bright.codified`), for example: `dev.bright.codified:enums:1.6.21.1`

Let me know if it worked for you.
